CREATE TABLE STUDENT(
RNO INT,
NAME VARCHAR(50),
BRANCH VARCHAR(50)
)
CREATE TABLE RESULT(
RNO INT,
SPI DECIMAL(4,2)
)

CREATE TABLE EMPLOYEES(
EMPLOYEENO VARCHAR(50),
NAME VARCHAR(50),
MANAGERNO VARCHAR(50)
)
--SOLUTION
--1
SELECT * FROM STUDENT CROSS JOIN RESULT
--7
SELECT * FROM STUDENT LEFT OUTER JOIN RESULT ON STUDENT.RNO=RESULT.RNO
--8
SELECT * FROM STUDENT RIGHT OUTER JOIN RESULT ON STUDENT.RNO=RESULT.RNO
--9
SELECT * FROM STUDENT FULL OUTER JOIN RESULT ON STUDENT.RNO=RESULT.RNO

--2


