--LAB2.2
--ANSWER1
UPDATE DEPOSIT SET AMOUNT=5000 WHERE AMOUNT=3000 
SELECT * FROM DEPOSIT
--ANSWER2
UPDATE BORROW SET BNAME='C.G. ROAD' WHERE CNAME='ANIL'
SELECT* FROM BORROW
--ANSWER3
UPDATE DEPOSIT SET ACTNO=111,AMOUNT=5000 WHERE CNAME='SANDIP'
--ANSWER4
UPDATE BORROW SET AMOUNT=AMOUNT+(0.1)AMOUNT
--ANSWER4
UPDATE DEPOSIT SET AMOUNT=5000 WHERE ACTNO>103 AND ACTNO<107
--ANSWER5
UPDATE 
