CREATE TABLE COMPUTER(
RollNo INT,
Name VARCHAR(50)
)
CREATE TABLE Electrical(
RollNo INT,
Name VARCHAR(50)
)
--SOLUTION
SELECT NAME FROM COMPUTER UNION SELECT NAME FROM ELECTRICAL
SELECT NAME FROM COMPUTER UNION ALL SELECT NAME FROM ELECTRICAL
SELECT NAME FROM COMPUTER INTERSECT SELECT NAME FROM ELECTRICAL
SELECT NAME FROM COMPUTER EXCEPT SELECT NAME FROM ELECTRICAL
SELECT NAME FROM ELECTRICAL EXCEPT SELECT NAME FROM COMPUTER
SELECT * FROM COMPUTER UNION SELECT * FROM ELECTRICAL
SELECT * FROM COMPUTER INTERSECT SELECT * FROM ELECTRICAL