CREATE TABLE CRICKET(
NAME VARCHAR(50),
CITY VARCHAR(50),
AGE INT
)
--SOLUTION
SELECT * FROM CRICKET
SELECT * FROM WORLDCUP
SELECT *FROM IPL

--1
SELECT * INTO WORLDCUP FROM CRICKET
--2
SELECT NAME,CITY INTO T20 FROM CRICKET WHERE AGE=0
--3
SELECT * INTO IPL FROM CRICKET WHERE 1=2
--4
INSERT INTO IPL SELECT * FROM CRICKET WHERE NAME LIKE '_A_____%'
--5
TRUNCATE TABLE IPL
--6
DELETE FROM CRICKET WHERE CITY='JHARKHAND'
--7
SP_RENAME 'IPL','IPL2018'
--8
DROP TABLE T20


