--LAB3
CREATE TABLE STUDENT(
ENROLLMENT_NO VARCHAR(20),
NAME VARCHAR(25),
CPI DECIMAL(5,2),
BIRTHDATE DATETIME)

--ANSWER1
ALTER TABLE STUDENT ADD CITY VARCHAR(20) NULL,BACKLOG INT NOT NULL
--ANSWER2
ALTER TABLE STUDENT ALTER COLUMN NAME VARCHAR(25)
--ANSWER3
ALTER TABLE STUDENT  ALTER COLUMN CPI INT
--ANSWER4
SP_RENAME 'STUDENT.ENROLLMENT_NO','ENO','COLUMN';
--ANSWER5
ALTER TABLE STUDENT DROP COLUMN CITY 
--ANSWER6
SP_RENAME 'STUDENT','STUDENT_MASTER'
--ANSWER7
ALTER TABLE STUDENT_MASTER DROP COLUMN BACKLOG
--ANSWER8
ALTER TABLE STUDENT_MASTER ALTER COLUMN NAME VARCHAR(35) NOT NULL
--ANSWER9
SP_RENAME 'STUDENT_MASTER.BIRTHDATE','BDATE','COLUMN'

--ANSWER10
ALTER TABLE STUDENT_MASTER ALTER COLUMN ENO VARCHAR(12)
